# Generated by Django 5.2 on 2025-04-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stipend', models.FloatField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='api.university')),
            ],
        ),
    ]
